# Generated by Django 4.1.2 on 2022-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='yt_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
