# Generated by Django 4.1.2 on 2022-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=155)),
                ('lastname', models.CharField(blank=True, max_length=155, null=True)),
                ('email', models.EmailField(max_length=155)),
                ('user_id', models.CharField(max_length=155)),
                ('company_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('subject', models.CharField(blank=True, max_length=155, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
